# We demand `txt`

We'll want to convert things like PDFs and Word files into plain text before we do stuff with them
in Python. This Jupyter Notebook will explore a couple of the ways we can do that using Python.

We'll use `pymupdf` to convert `pdf`s (and other things like `docx`) to text. First, we'll install
`pymupdf` with our usual

```uv add pymupdf```

From there its reletively straightforward. `pymupdf` cares about pages in our original document so
we'll have to use a loop to ensure we get all of the pages converted.

In [1]:
import pymupdf

document = pymupdf.open("2026_March 11 6:30 pm_Common Council CommitteeDeliberation Session.pdf")

my_pages = []
for page in document:
    my_pages.append(page.get_text().lower())

text = "\n".join(my_pages)
print(text)

city of bloomington common council agenda
and notice: deliberation session
wednesday, 6:30 pm, march 11, 2026
council chambers (#115), showers building
401 n. morton street, bloomington, in 47404
the meeting may also be accessed by zoom1
please click the embedded links in this agenda to access the referenced documents.
1. roll call
2. agenda summation
3. development of 2027 shared budget priorities
a.​ data from december 10 deliberation and follow up surveys
b.​ discussion of trends identified by the special fiscal committee
c.​ public comment
d.​ review of priority list
4. adjournment
bloomington city council meetings can be watched on the following websites:
●​ community action television services (cats)2
●​ city’s youtube channel3
materials for this meeting4 are available on council’s website.
4 https://bloomington.in.gov/council/meetings/2026
3 https://www.youtube.com/@citybloomington
2 https://catstv.net/
1
https://bloomington.zoom.us/j/81895656826?pwd=6onhkoyaxbbwwq33qap8rbuujcv
gzf.1
meeting id: 818 9565 6826 passcode: 801412
the city is committed to providing equal access to information. if you encounter
difficulties accessing material in this packet, please contact the office of the common
council at council@bloomington.in.gov and provide your name, contact information,
and a link to or description of the document or web page you are having problems with.
posted: march 4, 2026

We could then dump this into a file with our `with open(...)...:` syntax or whatever. We can get
all of the pdf files in a directory

In [2]:
document = pymupdf.open("2026_March 25 6:30 pm_Common Council Regular Session.pdf")

my_pages = []
for page in document:
    my_pages.append(page.get_text().lower())

text = "\n".join(my_pages)

# a list of keywords related to surveillance
flock_keywords = ["flock", "axon", "alpr"]

flock_mentioned = False
for keyword in flock_keywords:
    if keyword in text:
        flock_mentioned = True

print(flock_mentioned)

False

In [3]:
from pathlib import Path

pdfs = list(Path("../03_scraping/bloomington_city_council_agendas").glob("*.pdf"))

for pdf in pdfs:
    try:
        document = pymupdf.open(pdf)
    except:
        continue

    my_pages = []
    for page in document:
        my_pages.append(page.get_text().lower())  # type: ignore

    text = "\n".join(my_pages)

    # a list of keywords related to surveillance
    flock_keywords = ["flock", "axon", "alpr"]

    flock_mentioned = False
    for keyword in flock_keywords:
        if keyword in text:
            flock_mentioned = True

    if flock_mentioned:
        print(pdf)

../03_scraping/bloomington_city_council_agendas/2011_December 21 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2026_April 22 6:30 pm_Common Council Regular Session.pdf
../03_scraping/bloomington_city_council_agendas/2007_April 18 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2007_May 2 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2006_October 25 7:30 pm_Common Council Meeting.pdf
../03_scraping/bloomington_city_council_agendas/2006_October 18 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2011_December 7 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2007_April 25 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

MuPDF error: format error: No default Layer config

../03_scraping/bloomington_city_council_agendas/2011_December 14 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

MuPDF error: format error: No default Layer config

In [ ]:
import pandas as pd
def alpr_filter(text, date):

    flock_keywords = ["flock", "axon", "alpr"]

    flock_mentioned = False
    for keyword in flock_keywords:
        if keyword in text and date > pd.to_datetime("2022-01-01"):
            flock_mentioned = True

    return flock_mentioned

def police_filter(text):

    police_keywords = ["police", "bpd", "sergeant", "chief"]

    police_mentioned = False
    for keyword in police_keywords:
        if keyword in text:
            police_mentioned = True

    return police_mentioned

def extract_date(path):
    date_string = " ".join(path.stem.split("_")[:2])
    dt = pd.to_datetime(date_string)
    return dt


pdfs = list(Path("../03_scraping/bloomington_city_council_agendas").glob("*.pdf"))

my_pages = []
for pdf in pdfs:
    document = pymupdf.open(pdf)

    my_pages = []
    for page in document:
        my_pages.append(page.get_text().lower())

    text = "\n".join(my_pages)

    pdf_date = extract_date(pdf)

    if alpr_filter(text, pdf_date):
        print(f"flock mentioned in {pdf}")
    if police_filter(text):
        print(f"police mentioned in {pdf}")

police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_April 26 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_September 1 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2025_May 7 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_June 2 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2014_June 18 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_November 15 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_September 8 6:30 pm_Common Council Committee of the Whole and Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_July 11 6:30 pm_.pdf
MuPDF error: format error: No default Layer config

police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_October 13 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_May 18 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_June 7 6:30 pm_Common Council Regular Session (6:30pm) followed by a Committee of the Whole (8:00pm).pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_November 17 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1998_November 18 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2009_November 18 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_April 28 6:30 pm_Common Council Committee of the Whole.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_September 14 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_September 7 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_August 26 6:30 pm_.pdf
flock mentioned in ../03_scraping/bloomington_city_council_agendas/2026_April 22 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2026_April 22 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_September 29 6:30 pm_Common Council Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_September 11 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_December 2 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_June 21 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_August 16 6:00 pm_Common Council - Budget Hearings (Bloomington Housing Authority, Housing and Neighborhood Development, Economic and Sustainable Development, Community and Family Resources, Parks and Recreation).pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_April 10 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_July 24 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_May 6 12:00 pm_Common Council Work Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2011_September 14 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2009_December 16 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2010_December 8 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_June 21 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_August 19 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_September 28 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2007_December 5 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_November 14 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_December 6 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_December 4 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_May 24 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2024_October 16 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_October 27 6:30 pm_Common Council Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_November 3 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2009_December 9 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2024_November 6 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_November 6 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_October 13 6:30 pm_Common Council Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_August 20 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_February 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_November 17 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_November 5 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2007_September 5 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2010_December 1 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2019_December 4 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_January 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_August 17 6:00 pm_Common Council - Budget Hearings (Planning and Transportation, Public Works General, Animal Control, Fleet Maintenance, Traffic Control and Streets, Sanitation, Facilities).pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2009_January 21 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_September 26 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_November 4 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_November 16 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2014_October 8 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_August 29 5:30 pm_Departmental Budget Hearings on 2024 Budget.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_August 30 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2001_September 26 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_January 19 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_July 16 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_June 16 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_January 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2014_June 25 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_February 24 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_June 20 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_January 12 6:30 pm_Common Council Regular Session & Committee Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1998_October 14 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

police mentioned in ../03_scraping/bloomington_city_council_agendas/2025_August 18 5:30 pm_Common Council Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_November 16 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_August 18 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2008_November 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_July 25 6:00 pm_Common Council -- Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2001_July 25 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_May 28 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_November 30 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_October 23 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_July 24 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2012_September 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_December 1 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_November 15 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_August 31 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_September 6 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2013_October 9 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_December 8 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2014_July 2 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2008_September 10 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_August 31 5:30 pm_Departmental Budget Hearings on 2024 Budget.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_October 30 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_November 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2013_September 25 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_September 8 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_February 4 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2011_February 16 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_September 13 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2021_August 26 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2019_September 25 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_April 27 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_February 26 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_June 14 6:30 pm_Common Council Regular Session.pdf
MuPDF error: format error: No default Layer config

police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_November 30 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config

police mentioned in ../03_scraping/bloomington_city_council_agendas/1998_October 21 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_June 15 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_August 30 5:30 pm_Departmental Budget Hearings on 2024 Budget.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_December 9 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_February 18 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2010_September 15 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_June 8 6:30 pm_Common Council Committee Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_December 16 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2009_September 9 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2011_September 7 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_December 11 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2011_September 27 7:00 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_January 22 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_September 27 6:30 pm_Common Council Special Session followed by Committee of the Whole.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_July 21 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_June 28 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_January 18 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2006_November 1 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2025_April 16 6:30 pm_Common Council Regular Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_November 12 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_June 1 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2016_December 7 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_October 12 6:30 pm_Common Council Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2012_September 12 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_May 6 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_August 15 6:00 pm_Common Council - Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2005_December 7 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_August 17 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_July 19 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2001_May 16 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_July 10 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_March 22 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_November 29 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2004_December 15 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2001_September 5 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_October 2 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2017_January 11 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_October 8 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_October 10 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2020_October 14 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2014_July 9 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_September 10 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2001_July 18 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2003_May 21 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2022_September 1 6:00 pm_Departmental Budget Hearings.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_December 5 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2008_June 25 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2002_July 29 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2018_November 28 6:30 pm_.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2015_December 2 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2007_June 20 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2000_February 2 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/1999_February 17 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2019_December 3 6:00 pm_Council Special Session - Consideration of UDO Amendments.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2008_September 3 7:30 pm_Common Council Meeting.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2023_October 11 6:30 pm_Common Council Special Session.pdf
police mentioned in ../03_scraping/bloomington_city_council_agendas/2007_September 12 7:30 pm_Common Council Meeting.pdf
MuPDF error: format error: No default Layer config


In [ ]:
my_dates = pd.date_range(pd.to_datetime("2026-08-07"), pd.to_datetime("2026-08-11"))

df1 = pd.DataFrame({"my_dates": my_dates,
                   "urls": ["shaolin.com/wrist-chamber", "shaolin.com/arm-chamber", "shaolin.com/eye-chamber", "shaolin.com/foot-chamber", "shaolin.com/head-chamber"],
                   "description": ["wrist", "arm", "eye", "foot", "head"]})

df1

    my_dates                       urls deascription
0 2026-08-07  shaolin.com/wrist-chamber        wrist
1 2026-08-08    shaolin.com/arm-chamber          arm
2 2026-08-09    shaolin.com/leg-chamber          leg
3 2026-08-10   shaolin.com/foot-chamber         foot
4 2026-08-11   shaolin.com/head-chamber         head

In [21]:
my_other_dates = list(my_dates.copy())
my_other_dates.append(pd.to_datetime("2026-08-12"))

df2 = pd.DataFrame({"my_dates": my_other_dates[2:],
                    "cool_filter": [True, False, False, True]})

df2

    my_dates  cool_filter
0 2026-08-09         True
1 2026-08-10        False
2 2026-08-11        False
3 2026-08-12         True

In [26]:
pd.merge(df1, df2, how="left")

    my_dates                       urls deascription cool_filter
0 2026-08-07  shaolin.com/wrist-chamber        wrist         NaN
1 2026-08-08    shaolin.com/arm-chamber          arm         NaN
2 2026-08-09    shaolin.com/leg-chamber          leg        True
3 2026-08-10   shaolin.com/foot-chamber         foot       False
4 2026-08-11   shaolin.com/head-chamber         head       False