# The DataFrame

Basically 100% of the time we're doing data analysis, we're working with
DataFrames. The `pandas` library provides the DataFrame object and basically
enables all data work in Python. DataFrames are pretty straightforwardly tables
in the sort of spreadsheet sense. `pandas` is aware of what a 'column' is and
provides a lot of ways to filter and clean data.

Just like numpy you may need to install pandas. Use `ctrl` + `~` to open the command terminal. Type `source .venv/bin/activate` hit `Enter` then type `python3 -m pip install pandas` hit `Enter`. Now numpy is installed in your virtual environment!

First, I'll show how we make one from scratch so we have an easy dataframe to
explore functionality with.

In [ ]:
import pandas as pd
import numpy as np

# dataframes are amazing
category = ["vowel", "consonant", "consonant", "consonant", "vowel", "consonant", "consonant", "consonant"]
my_df = pd.DataFrame({"labels": ["a", "b", "c", "d", "e", "f", "g", "h"],
                      "numbers": np.random.normal(size=8),
                      "category": category})
print("This is my DataFrame:")
print(my_df)

This is my DataFrame:
  labels   numbers   category
0      a -1.144452      vowel
1      b -0.336538  consonant
2      c  0.911257  consonant
3      d -0.596250  consonant
4      e -0.132083      vowel
5      f  1.411550  consonant
6      g  0.705667  consonant
7      h  1.988019  consonant

We can add new columns to our dataframe by just pretending it exists and
assigning a value to it. The value MUST be the same length as the other columns!

In [ ]:
my_df["big_numbers"] = np.random.normal(loc=10, size=8)
my_df

  labels   numbers   category  big_numbers
0      a -1.144452      vowel     9.180288
1      b -0.336538  consonant    10.447744
2      c  0.911257  consonant    10.818491
3      d -0.596250  consonant    10.506296
4      e -0.132083      vowel    11.431935
5      f  1.411550  consonant    10.563079
6      g  0.705667  consonant    11.087965
7      h  1.988019  consonant     8.846891

Often, we will want to know some basic info about our dataframe. Two pieces
of information that are really helpful are the `.info()` method, and the .`shape`
attribute

In [ ]:
my_df.shape

(8, 4)

This shows us the number of rows then the number of columns. Sometimes we need
to use these numbers in code we're writing and this allows us to access them
programmatically.

In [ ]:
my_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   labels       8 non-null      str
 1   numbers      8 non-null      float64
 2   category     8 non-null      str
 3   big_numbers  8 non-null      float64
dtypes: float64(2), str(2)
memory usage: 388.0 bytes

`.info()` is more helpful for when we want to visually inspect the overall
picture of our data. It first lists the number of rows (`RangeIndex:`), then the
number of columns `Data Columns`. Then it tells us each column's name and the
number of real values in that column and the column's type. Missing or *null*
values will be a problem for us when we get our hands on real data.

### Selecting rows and columns

Because dataframes are aware that we want to think about our data as tables, `pandas` has made it incredibly easy to select a column

In [ ]:
# we can kind of think of it a little bit like a dictionary of numpy arrays
# we call the the key-value pair a column
print("My 'labels' column is:")
print(my_df["labels"])

My 'labels' column is:
0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
Name: labels, dtype: str

We can even select multiple columns at the same time using a list of column
names rather than a single column name.

In [ ]:
my_df[["labels", "category"]]

  labels   category
0      a      vowel
1      b  consonant
2      c  consonant
3      d  consonant
4      e      vowel
5      f  consonant
6      g  consonant
7      h  consonant

The numbers on the left next to our column values are called the Index. We can
use the Index to select rows rather than columns. We will use `iloc` to select
rows using the Index (if the Index is an integer as it is here). In cases where
our Index is a string, which might come up occasionally, we will use `loc`
instead.

> side note: the Index can be very powerful. `pandas` gives us lots of ways of
> doing things and I typically avoid using the Index when possible. some people
> love it

In [ ]:
my_df.iloc[2]

labels                 c
numbers         0.911257
category       consonant
big_numbers    10.818491
Name: 2, dtype: object

The format looks a little different (it prints the row vertically like a column)
but if you check against the table you should find that it matches with the
table we printed out earlier.

We can use the Index along with a column name to select individual values

In [ ]:
my_df.iloc[2]["category"]

'consonant'

In [ ]:
# Now try using the index to locate the row f and select the "big numbers" value.
my_df.iloc[5]["big_numbers"]

np.float64(10.563078599668255)

### Element-wise operations

One of the core features of `pandas` is the ability to do element-wise
operations on columns, much like numpy arrays. This means we can write a single statement and without
looping, do the operation on each row of the dataframe column

In [ ]:
# this will double each number in the "numbers" column|
print(my_df["numbers"])

print(my_df["numbers"] * 2)

0   -1.144452
1   -0.336538
2    0.911257
3   -0.596250
4   -0.132083
5    1.411550
6    0.705667
7    1.988019
Name: numbers, dtype: float64
0   -2.288905
1   -0.673076
2    1.822513
3   -1.192501
4   -0.264166
5    2.823100
6    1.411333
7    3.976038
Name: numbers, dtype: float64

We can do something similar using two columns rather than one column and a
literal value.

In [ ]:
my_df["labels"] + my_df["category"]

0        avowel
1    bconsonant
2    cconsonant
3    dconsonant
4        evowel
5    fconsonant
6    gconsonant
7    hconsonant
dtype: str

We can even combine element-wise operations with helpful built-in column methods.

For example we can rescale a column based on the maximum value in a single line of code.

In [ ]:
my_df["numbers"] / my_df["numbers"].max()

0   -0.575675
1   -0.169283
2    0.458374
3   -0.299922
4   -0.066439
5    0.710029
6    0.354960
7    1.000000
Name: numbers, dtype: float64

Not helpful in this case but still pretty cool to be able to do that. It will be
much more useful when we see dataframes with more interesting columns.

For reasons that will hopefully soon be very obvious, the most important
element-wise operations we can do are conditional statements. 

Lets create a mask variable. 
Instead of merely printing the result of our element-wise operation, lets also assign it to a
variable. We'll use it a little later.

In [ ]:
positive_numbers = my_df["numbers"] > 0
positive_numbers

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7     True
Name: numbers, dtype: bool

We get a column of boolean values when we do this. We can use this to *filter* our data.

### Filtering data

dataframes can also use so-called fancy indexing that we learned about in numpy arrays. In most cases, we will do
fancy indexing with boolean arrays like the one we've just constructed. When we
use a boolean array to index, we call it *masking* with the boolean array being
called a *mask*.

In [ ]:
# we can use fancy indexing to pull out specific rows
my_df[positive_numbers].reset_index()

   index labels   numbers   category  big_numbers
0      2      c  0.911257  consonant    10.818491
1      5      f  1.411550  consonant    10.563079
2      6      g  0.705667  consonant    11.087965
3      7      h  1.988019  consonant     8.846891

Unless we're using a complicated set of conditionals with multiple `and`s and `or`s we usually don't bother giving the mask its own variable (but feel free if it helps you). Instead we'll just put the conditional directly in the square braces used to call the index.

In [ ]:
my_df[my_df["numbers"] > 0]

  labels   numbers   category  big_numbers
2      c  0.911257  consonant    10.818491
5      f  1.411550  consonant    10.563079
6      g  0.705667  consonant    11.087965
7      h  1.988019  consonant     8.846891

In doing this fancy indexing, we've pulled out just the rows of the dataframe
for which the numbers column is positive. Its really helpful to be able to
perform this kind of filtering so easily. If we wanted to do this using lists
everytime we wanted to filter we would die before we ever got to anything cool.

Often we will want to pull out a single column after filtering. We can do this
by using the same syntax we used to select a column stuck on the end of our
fancy indexing with additional square braces.

In [ ]:
my_df[my_df["numbers"] > 0]["labels"]

1    b
3    d
5    f
6    g
Name: labels, dtype: object

## Data Frame Lab ~ A Dozen Dead Cops ~

Let's use all our new skills to analyze this totally made up data set about cop deaths!! (Note that data about salaries and over time pay are based off real values.)

We have provided some lists with data about cops, the info is all related by index.

In [ ]:
# only good cop is a dead cop

# We have all our data as lists currently. Use them to create a data frame.abs

name = ["James", "Timothy S. Dolan", "Matthew", "Deedee Megadoodoo", "Christopher", "Andrew", "Sarah", "Thomas", "Michael", "Mark", "Robert", "Richard"]

city = ["Minneapolis", "Oakland", "New York", "Louisville", "Los Angelos", "New York", "New York", "Atlanta", "Minneapolis", "Atlanta", "Atlanta", "Chicago"]

cause_of_death = ["Car Crash", "Exploded", "Friendly Fire", "Friendly Fire", "Heart Attack", "Heart Attack", "Decapitated", "Friendly Fire", "Exploded", "Exploded", "Touching Fentanyl", "Shoot Out"]

number_filed_complaints = [203, 3855, 476, 1052, 1312, 327, 7068, 935, 287, 493, 5328, 855]

marriage_status = [ "Divorced", "Single", "Divorced", "Divorced", "Single", "Divorced", "Divorced", "Divorced", "Divorced", "Divorced", "Divorced", "Divorced"]

Blood_Alcohol_Concentration_at_TOD = [0.11, 0.00, 0.04, 0.23, 0.18, 0.01, 0.09, 0.00, 0.08, 0.00, 0.29, 0.35]

rank = ["Officer", "Officer", "Lieutenant", "Officer", "Sergeant", "Officer", "Sergeant", "Lieutenant", "Sergeant", "Sergeant", "Lieutenant", "Sergeant"]

annual_salary = [97742, 106000, 160884, 153163, 143117, 60532, 93273, 70540, 126410, 98320, 84732, 91400] 

annual_overtime_pay = [150670, 493247.34, 102050, 98040, 170900, 32700, 27005, 30090, 40070, 26790, 43040, 25700]

# create a data frame here
dead_cop_df = []

Now that you have a data frame, lets figure out how the cop with the largest annual salary died, print out his name, salary, and cause of death. 


Then calculate the effective annual salary by combing the overtime pay and salary. Add it to your data frame. Now find the cause of death of the cop with the largest effective annual salary. Print out their name, efective salary, and cause of death.

In [ ]:
# Find the cop with the largest salary.
# hint we can use .max 
# print out the name, cause of death, and salary of cop with largest salary
print("Cop with the largest salary:")
print()

# now calculate the efective annualy salary by adding the salaray and over time together and add it to your data frame




# print out the name, cause of death, salary, and city of the cop with the larest effective salary
print("cop with the largest effective salary:")

Cop with the largest salary:
     names          death  salary
2  Matthew  Friendly Fire  160884
cop with the largest effective salary:
              names     death  salary
1  Timothy S. Dolan  Exploded  106000

We can create a mask to figure out how much money was saved nationally by 
the death of divorced cops that died by exploding. We will need to create a more
complicated mask in order to do this! Then we will need to sum up their effective annual salaries.

In [ ]:
# hints 
# the equal operator is ==
# the or operator is  | 
# the and operator is &
# to compare two different comparison operations we need to place them each in parenthesis
# example: ( mydf["numbers">0] ) & (mydf["numbers"==-2])


# it may be easier to create multiple masks

The nation saved $906,357.00 this year!